version: 2
checks:
  similar-code:
    enabled: false
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
exclude_patterns:
  - "**/node_modules"
  - "**/__snapshots__"
  - ".storybook"
  - "lib"
  - "src/setupTests.js"
  - "src/**/*.css"
  - "stories"
